print("TOKO MAINAN ANAK")
print("=============================")
nama=input("Masukan Nama Pembeli :")
kode=input("Kode Mainan :")
jumlah_beli=(int(input("Jumlah Beli:")))
harga=int(input("Harga Satuan :"))
print("===============================")

print("Nama Pembeli :", nama)
print("Kode Mainan :", kode)
print("Harga satuan", harga)
print("Jumlah Beli", jumlah_beli)
total_harga=(jumlah_beli*harga)
print("Total Harga :",total_harga)
total_bayar=(int(input("Total Bayar :")))

uang_kembali=(total_bayar-total_harga)
print("Uang Kembalian :", uang_kembali)
print("====================================")
